#!/usr/bin/env bash
# dev.sh - start, stop and inspect the External App (backend + frontend) with one command.
#
#   ./dev.sh up        start the backend (FastAPI + SQLite) and the frontend (Next.js)
#   ./dev.sh down      stop both (the database file is kept)
#   ./dev.sh status    show what is running
#   ./dev.sh logs [backend|frontend]   follow the logs (both, or one)
#
# The CrewAI flow is NOT started here: it runs on CrewAI AMP (see README.md). The frontend only
# needs its address and token in external_app/frontend/.env.local.
# Ports and addresses come from the .env files of each project. `up` prints a WARNING for the settings
# that would make the import fail (see "Configuration and ports" in README.md).

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKEND_DIR="$ROOT/external_app/backend"
FRONTEND_DIR="$ROOT/external_app/frontend"
RUN_DIR="$ROOT/.run" # pid files and logs of the services

# ---------- helpers ----------

say() { printf '%s\n' "$*"; }
fail() { printf 'ERROR: %s\n' "$*" >&2; exit 1; }

# Read KEY from a .env file. Falls back to the default when the file or the key is missing.
env_value() {
  local file="$1" key="$2" default="$3" value=""
  if [[ -f "$file" ]]; then
    value="$(grep -E "^${key}=" "$file" | tail -n 1 | cut -d= -f2- | sed 's/[[:space:]]*#.*//' | tr -d '"'"'" || true)"
  fi
  printf '%s' "${value:-$default}"
}

# Create a .env file from its example when it does not exist yet.
ensure_env() {
  local dir="$1" target="$2"
  if [[ ! -f "$dir/$target" && -f "$dir/.env.example" ]]; then
    cp "$dir/.env.example" "$dir/$target"
    say "  created $dir/$target from .env.example"
  fi
}

require() { command -v "$1" >/dev/null 2>&1 || fail "'$1' is not installed. $2"; }

is_up() { curl -fs -m 2 -o /dev/null "$1"; }

wait_for() {
  local name="$1" url="$2" seconds="$3" log="${4:-}"
  say "  waiting for $name ($url)..."
  for ((i = 0; i < seconds; i++)); do
    is_up "$url" && { say "  $name is up"; return 0; }
    sleep 1
  done
  [[ -n "$log" && -f "$log" ]] && { say "--- last lines of $log"; tail -n 15 "$log"; }
  fail "$name did not answer at $url after ${seconds}s"
}

api_port()      { env_value "$BACKEND_DIR/.env" API_PORT 8000; }
frontend_port() { env_value "$FRONTEND_DIR/.env.local" FRONTEND_PORT 3000; }

backend_url()  { printf 'http://localhost:%s/health' "$(api_port)"; }
frontend_url() { printf 'http://localhost:%s/' "$(frontend_port)"; }

# ---------- up ----------

up_backend() {
  say "backend (FastAPI + SQLite)"
  require uv "Install uv (https://docs.astral.sh/uv/)."
  if is_up "$(backend_url)"; then say "  already running, skipping"; return; fi
  ensure_env "$BACKEND_DIR" .env
  # Without the secret of the HITL webhook (generated by AMP), the API refuses every review request.
  [[ -n "$(env_value "$BACKEND_DIR/.env" CREWAI_HITL_WEBHOOK_SECRET "")" ]] \
    || say "  WARNING: CREWAI_HITL_WEBHOOK_SECRET is empty in external_app/backend/.env: the review webhook will be refused (503)"
  [[ -d "$BACKEND_DIR/.venv" ]] || {
    say "  installing dependencies (uv)..."
    (cd "$BACKEND_DIR" && uv venv -q .venv && uv pip install -q --python .venv/bin/python -r requirements.txt)
  }
  # Own process group, so `down` can stop uvicorn and its reloader together.
  mkdir -p "$RUN_DIR"
  (cd "$BACKEND_DIR" && setsid nohup .venv/bin/uvicorn app.server:app --reload --port "$(api_port)" >"$RUN_DIR/backend.log" 2>&1 </dev/null & echo $! >"$RUN_DIR/backend.pid")
  wait_for "backend" "$(backend_url)" 60 "$RUN_DIR/backend.log"
}

up_frontend() {
  say "frontend (Next.js)"
  require npm "Install Node.js 20 or newer."
  if is_up "$(frontend_url)"; then say "  already running, skipping"; return; fi
  ensure_env "$FRONTEND_DIR" .env.local
  # The flow runs on CrewAI AMP: without its address and token the import page cannot work.
  grep -Eq '^CREWAI_FLOW_API_URL=https?://' "$FRONTEND_DIR/.env.local" \
    || say "  WARNING: set CREWAI_FLOW_API_URL and CREWAI_FLOW_API_BEARER_TOKEN in external_app/frontend/.env.local (the flow is on CrewAI AMP)"
  # AMP sends the webhooks of each run to EXTERNAL_APP_API_URL, from the internet: the Next.js proxy refuses a kickoff when it is localhost.
  [[ "$(env_value "$FRONTEND_DIR/.env.local" EXTERNAL_APP_API_URL "")" =~ ^https?://(localhost|127\.0\.0\.1) ]] \
    && say "  WARNING: EXTERNAL_APP_API_URL is localhost in external_app/frontend/.env.local: AMP cannot reach it, so a kickoff is refused (use the ngrok address)"
  # AMP gives this secret back to the backend with the events, so both sides must have the same one.
  [[ "$(env_value "$FRONTEND_DIR/.env.local" CREWAI_KICKOFF_WEBHOOK_SECRET "")" == "$(env_value "$BACKEND_DIR/.env" CREWAI_KICKOFF_WEBHOOK_SECRET "")" ]] \
    || say "  WARNING: CREWAI_KICKOFF_WEBHOOK_SECRET is not the same in external_app/backend/.env and external_app/frontend/.env.local"
  [[ -d "$FRONTEND_DIR/node_modules" ]] || { say "  installing dependencies (npm install)..."; (cd "$FRONTEND_DIR" && npm install --silent); }
  # Own process group, so `down` can stop npm and the Next.js server together.
  mkdir -p "$RUN_DIR"
  (cd "$FRONTEND_DIR" && setsid nohup npm run dev -- -p "$(frontend_port)" >"$RUN_DIR/frontend.log" 2>&1 </dev/null & echo $! >"$RUN_DIR/frontend.pid")
  wait_for "frontend" "$(frontend_url)" 90 "$RUN_DIR/frontend.log"
}

# ---------- commands ----------

cmd_up() {
  up_backend
  up_frontend
  say ""
  say "Open:"
  say "  App (frontend)   http://localhost:$(frontend_port)"
  say "  Contacts API     http://localhost:$(api_port)/docs"
  say ""
  say "Logs: ./dev.sh logs [backend|frontend]    Stop: ./dev.sh down"
}

# Stop a service started by `up`. A negative pid means "the whole process group" (npm and uvicorn
# start child processes).
stop_service() {
  local name="$1" url="$2" pidfile="$RUN_DIR/$1.pid"
  say "$name"
  if [[ -f "$pidfile" ]]; then
    kill -TERM -- "-$(cat "$pidfile")" 2>/dev/null || true
    rm -f "$pidfile"
    say "  $name stopped"
  elif is_up "$url"; then
    say "  $name is running, but it was not started by dev.sh. Leaving it alone."
  else
    say "  $name is not running"
  fi
}

cmd_down() {
  stop_service frontend "$(frontend_url)"
  stop_service backend "$(backend_url)" # the database (external_app/backend/data/) is kept
}

cmd_status() {
  for entry in "backend|$(backend_url)" "frontend|$(frontend_url)"; do
    local name="${entry%%|*}" url="${entry#*|}"
    if is_up "$url"; then printf '  %-9s UP    %s\n' "$name" "$url"; else printf '  %-9s DOWN  %s\n' "$name" "$url"; fi
  done
}

cmd_logs() {
  case "${1:-}" in
    "")       [[ -f "$RUN_DIR/backend.log" || -f "$RUN_DIR/frontend.log" ]] || fail "no logs yet. Run ./dev.sh up first."
              tail -n 20 -F "$RUN_DIR"/*.log ;;
    backend|frontend)
              [[ -f "$RUN_DIR/$1.log" ]] || fail "no log for '$1' (it was not started by dev.sh)."
              tail -n 50 -F "$RUN_DIR/$1.log" ;;
    *)        fail "unknown service '$1'. Use: backend or frontend" ;;
  esac
}

usage() { sed -n '2,12p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; }

case "${1:-up}" in
  up|down|status)
    [[ $# -le 1 ]] || fail "'$1' takes no arguments (it always handles the backend and the frontend)."
    "cmd_${1:-up}" ;;
  logs)   shift; cmd_logs "$@" ;;
  -h|--help|help) usage ;;
  *) usage; exit 1 ;;
esac
